# Genesis
GENESIS_FORK_VERSION: 0x01017000
GENESIS_VALIDATOR_ROOT: ""
# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x3e839677d23d9b7b0df00ed0c67750aa6412b75d
MAX_EFFECTIVE_BALANCE: 1024000000000  #gwei
