CONFIG_NAME: interop
PRESET_BASE: interop

# Genesis
GENESIS_FORK_VERSION: 0x01017000

# Altair
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090

# Merge
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 0

# Capella
CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000092
MAX_WITHDRAWALS_PER_PAYLOAD: 16
MAX_EFFECTIVE_BALANCE: 1024000000000  #gwei

DENEB_FORK_VERSION: 0x20000093

# Time parameters
SECONDS_PER_SLOT: 6
SLOTS_PER_EPOCH: 32

BASE_REWARD_FACTOR: 128

ETH1_FOLLOW_DISTANCE: 2
EPOCHS_PER_ETH1_VOTING_PERIOD: 1
# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x3e839677d23d9b7b0df00ed0c67750aa6412b75d